on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'psalm.xml'

name: Mutation test

jobs:
  rabbitmq:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          ports: '1883:1883 8883:8883'
  mutation:
    uses: yiisoft/actions/.github/workflows/roave-infection.yml@master
    with:
      os: >-
        ['ubuntu-latest']
      php: >-
        ['8.0', '8.1', '8.2']

    secrets:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 1883
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
